export const operationsSchema = {
  "coverage": {
    "id": "tblnlI4rYUkpIBDX0",
    "fields": {
      "Coverage Request": "fldhOZcD7bz5uouw2",
      "Client": "fldhN7NobCe4Lf0zn",
      "Role": "fldV1JHATmVmBlibK",
      "NEXT State": "fldWijOjjKxLe4YGC",
      "Shift Date": "fldeGeqe6XZqiZP7r",
      "Location": "fldVyJuXgkMSRtsQU",
      "Assigned Worker": "fldHVSGuz2FYKBtGR",
      "Missing Pieces": "fldvKW7NbQiQvzvCV",
      "Notes": "fldbbIAvOqrUiaM3H",
      "Start Time": "fldoeBo6aWKoc2vL9",
      "End Time": "fldCK0fyjYeY3I3uZ",
      "On Site Contact": "fldmvGLrtShOPa9yh",
      "Object ID": "fldA5auW9QxYUl6Ff",
      "Client Record": "fld8EafjLWGmgtXcj",
      "Worker Records": "fldbmlkEtOrLS3ioD",
      "Attendance Outcome": "fldYs8nCSYCouKtpX",
      "Backup Worker": "fldofPiYY8T8niV7p",
      "Verified Hours": "fldpymiPGszjAoDNJ",
      "Hours Evidence Verified": "fld8x0YmfJkqRsLmS",
      "Payroll Cycle Link": "fldk0pdGLjLoJyzcS",
      "Invoice Link": "fld9nzUDGZ62khRj5",
      "Original Assigned Worker": "fldunNTSp3xVcT8ms",
      "Replacement Worker": "fldGsOzXkOcwJmQ4z",
      "Incident Type": "fldZyJiUSp2S2oM2m",
      "Recovery Status": "fld3O18KQprfQvcwt",
      "Evidence Records": "fld1pvxda7qWyQaIi",
      "Correction Records": "fldVPPW4AW9rJgLrB",
      "Source Client Intake": "fldEvfgjSeHChQZHI",
      "Recruiting Matching Runs": "fld6e6X3LNShO6f6H",
      "Recruiting Opportunity Matches": "fldo3dPKSmxERvtyp",
      "Assignment Type": "fldPYUTKVOpvFP0Tt",
      "Urgency": "fldo3dpCBRiVHOe5G",
      "Request Received At": "fld7Q0ILJcxHBWn1C",
      "Coverage Group / Batch ID": "fld472SXIcCrDtBNm",
      "Worker Slot Number": "fldq0IqzpnSYsLtS7",
      "Dress Code": "fldldyFoyiPKmvolw",
      "Check-in Instructions": "fld3OVpsjRiwGJQAe",
      "Reporting Location": "fld9tRLbeZd0MHy9g",
      "Parking / Access Details": "fldAmIiKTYtjfhuJ3",
      "Client Confirmation Status": "fldt6glSoSd16b3FE",
      "Worker Confirmation Status": "fld5kAFW61fIZTeEG",
      "Dispatch Sent At": "fld46cxpgs0sfXCwj",
      "Dispatch Acknowledged At": "fldK6syOOSoYFqMKb",
      "Approved Worker Rate Snapshot": "flddtM910uigg4G6i",
      "Approved Client Rate Snapshot": "fldoSlyp2wD2YMZet",
      "Rate Evidence Status": "fld9VtTTXBWsd80nn",
      "Tips / Breaks / Compensation Notes": "fldLcTjn8P4WSGuUz",
      "Finance Control Records": "fldi6bgkFD6kFsqdl",
      "Dispatch Authorized At": "fldYysTMfxFbYZasR",
      "Record Environment": "fldwScW8OSMUnoNWo",
      "Email Intake": "fldx4UmlYEHUbuHdF",
      "Source Event ID": "fldILK2MuIHBoSxcY",
      "Coverage Record Type": "fldWccYpWQLAQyqUq",
      "Required Headcount": "fldU9uTv8a8IFg5Fw",
      "Parent Demand Coverage": "flddGiYAUM2DePueY",
      "From field: Parent Demand Coverage": "fldVTTEZcstqYxBrB",
      "Assignment Sequence": "fldunwA7dFNQI5Q9Y",
      "Worker Bookings": "flduC3mM4oSruxluw",
      "Shift Block Sequence": "fldeuqYFvC92yG3jK",
      "Current Worker Booking": "fldu2oxVb8HHqjAcd",
      "Worker Reported Hours": "fldnyOlxnS8hubHIm",
      "Client / Supervisor Confirmed Hours": "fldJNXzxn4msu7mvY",
      "Break Hours": "fldrj1KrKLUREYShI",
      "Time Verification Method": "fldXJVRIjGIuknxbx",
      "Time Verification Status": "fldWG9NQrBXUHV39y",
      "Scheduled Hours": "flduwEIBoPDMtXCDt",
      "Fulfillment Requirement Version": "fld2NH5P8tfxJ6hGt",
      "Job Alert Fallback Status": "fldADUcVUGHEpHGuq",
      "Job Alert Trigger Reason": "fldC0diUBg4akJE6F",
      "Job Alert Content Items": "fldNPzbPrLv1E7GYu",
      "Recruiting Assignment Fit Verified": "flduWKT49yjWjv6qB",
      "Recruiting Assignment Fit Verified At": "fldkdvHNeIGfxZ9eA"
    }
  },
  "payroll": {
    "id": "tbl4hdO6xJa0jFC3V",
    "fields": {
      "Payroll Cycle": "fldcBaPceZTuVoLpN",
      "Client": "fldW024ZJGrGAo1tL",
      "Worker": "fldTZnbSluQfVYwEs",
      "NEXT State": "fldEMmtC5v3b4pfQ9",
      "Gate Status": "fld84TNPjAVgF7T1v",
      "Period Start": "fldp5gmxTnfwlgCjp",
      "Period End": "fldmmEEL9yb4curE9",
      "Hours": "fldr076jg4B9iroMC",
      "Rate": "fldvJlrnW2CCxtVhg",
      "Gross Pay": "fldktChpiGbGoLjZg",
      "Client Payment Status": "fldwLUthwG6epJS9O",
      "Worker Payment Status": "fldemGDLWADNjC6AD",
      "Missing Pieces": "fld4NHi3VdpkZE1Z7",
      "Next Task": "fldPV911ZgQcHrBEw",
      "Notes": "fldw3mIHIxXJcPgJ2",
      "Object ID": "fldhfy8nHFrMcYFrE",
      "Workers": "flduX5rm94R1tqcfY",
      "Client Record": "fld62fkVYEz9JLtVX",
      "LEGACY — Worker Records — DO NOT USE": "fldy3b1HqJsV3L1YP",
      "Tasks": "fldyH4PenPaQQbwnD",
      "Alarms": "fldA1Unk7014PbX4I",
      "Calculated Gross Pay": "fldq3iro5jfljGOh9",
      "Gross Pay Variance": "fldfdYfQQtTwFMLbb",
      "Coverage Requests": "fldttJjxTdewf0xOt",
      "Hours Evidence Verified": "fld6gdUzXgvRUL7n1",
      "Payment Authorized": "fldIJYvKhDJTpzG3o",
      "Payroll Release Gate": "fldzUAM4bIPNfq6AM",
      "Invoices": "fldDwKibljYaLMRpL",
      "Finance Control": "fld1xcZRFy2bBR2ZH",
      "Evidence Records": "fldTj9fxXkf6h3xZN",
      "Command Ledger Records": "fldnYwbYh0dyEwaoI",
      "Result Check Records": "fld1uw4aAM0CAsGy0",
      "Correction Records": "fldGNFnEDFnZARWFA",
      "Airtable Record ID — Immutable": "fld2ruwBJ3O8El2k2",
      "Record Environment": "fldScs776oo854Jpi",
      "Email Intake": "fldywCvJJZ7u2fBAc",
      "Q3 — Rate Evidence": "flddydXKP6h5WYI6V",
      "Q6 — Worker Payment Evidence": "fldm8Rh7R1LPJrJN7",
      "Q7 — Finance Reconciliation": "fldmyICO2tSmG191w",
      "Guided Review Owner": "fldMWE4hkAmDWokww",
      "Guided Review Completed At": "fldCoK2hblEELqwF5",
      "Coverage Record ID Snapshot": "fldYx5HeDHkscOruP",
      "Coverage Verified Hours Snapshot": "fldEQPgzuxMB0wMuh",
      "Coverage Time Gate Snapshot": "fldk9Foi2ygHe1KKf",
      "Coverage Completion Gate Snapshot": "fldlLWaNKaGPGwObJ",
      "Coverage Time Handoff Gate": "fld6e9OCzYDDWTvTI",
      "Payment Settlement Status": "fldz868KByN91rKY4",
      "Payment Event ID": "fldhd12s3EIbrHZIf",
      "Settled Amount": "flduqqgb10k55m4CX",
      "Payment Settlement Evidence Verified": "fldcSISSziUY7PkHq",
      "Remaining Worker Liability": "fldxMEj4iS6IuFWxH",
      "Worker Deduction / Adjustment": "fldbti7bXOb24Uubj"
    }
  },
  "invoices": {
    "id": "tblqgnRAMgTL5qldZ",
    "fields": {
      "Invoice Number": "fldovgooTMKpk4Jmr",
      "Client": "fldzjQEL025uln7Ln",
      "Billing Period": "fldn7A0bdhm5Jfo22",
      "Period Start": "fldr41Bair7Q2Q0XS",
      "Period End": "fldXJDnku8pRI0bro",
      "Service Label": "fldtG4Zg5iymcQ1u1",
      "Total Amount": "fldh1HILwPCZX5ppv",
      "Invoice Status": "fldq2QXISe4gOQrNv",
      "Notes": "fldnefllDvyygNkjK",
      "Billable Hours": "fld9tWnLef4csHWNZ",
      "Bill Rate": "fld5yWusxWXhcsOVs",
      "Calculated Invoice Total": "fldnYNJ4ostpD86cc",
      "Invoice Total Variance": "fld15vewe8Yn7YLD1",
      "Coverage Requests": "fldVAOuUV1uR663RC",
      "Billing Evidence Verified": "fldRle2ViE8Ec20vA",
      "Send Authorized": "fldvDSA31SmIhbL4N",
      "Payroll Cycles": "fld4eCWYId7nUXvT0",
      "Invoice Match Key": "fldMmmhpL54OS9EXx",
      "Invoice Send Gate": "fldhGoGcYAqheKekV",
      "Finance Control": "fldYDKwAeF2HtCEFD",
      "Invoice Registry": "fldtisR4z9QpWSLXx",
      "Registered Token": "fldCb16CDPo2MA9HZ",
      "Expected Registry Token": "fldXtu0Y1AkwVY64s",
      "Registry Validation": "fldw17mnjwfk8Dzem",
      "Invoice Number Registry": "fldYm1bPM70KFZ0Uk",
      "Registered Number Token": "fldDKdgoviQfmDoZ7",
      "Expected Number Token": "fldmsS55KbAB04EFr",
      "Number Registry Validation": "fldWlYDsAT6SxACgd",
      "Client Record": "fldl81imw2Mp78uJ4",
      "Evidence Records": "fldrMv1LX16Lfu108",
      "Command Ledger Records": "fldv8K0GrH7woEJGs",
      "Correction Records": "fld9Jv2SjWRVGAlbx",
      "State Transition Records": "fldEOfBvbPGroIkLw",
      "Record Environment": "fldIsK6tikWYOWoBa",
      "Email Intake": "fldSyjROKew9AEGqm",
      "Invoice Calculation Mode": "fldZ4J8aBn4pMtAib",
      "Authorized Non-Hours Amount": "fldSZjweKViRd0627",
      "Authorized Non-Hours Line Description": "fld3zMWFgDU3bLA9i",
      "Non-Hours Billing Evidence": "flduWwagltThdkubH",
      "Invoice Calculation Path Gate": "fldDmvF9J4Rn0KyBt",
      "Invoice Template Version Snapshot": "fldYfUEO2Gnyz96yo",
      "Invoice Template Drive File ID": "fld3lW86aMN0HbL1v",
      "Invoice Draft Drive File ID": "fldfW2dnauIGgQNme",
      "Invoice Draft Render Gate": "fldcgG7wmGRlnE4iN",
      "Invoice Recipient Route Snapshot": "fldgnxjmHbj3CH9PL",
      "Invoice Recipient Validation": "fldxxpp0PsJtyNTfl",
      "Invoice Send Effect ID": "fldFFcxJLTyDaWcjd",
      "Invoice Delivery Status": "fldv51JK3dVxhgsR3",
      "Invoice Delivery Evidence Verified": "fldaTwuvvZHA2C7RY",
      "Invoice Receivable Settlement Status": "fldj0Wk6OEmbFFqNk",
      "Invoice Receivable Settled Amount": "fldA3YicD0tkOBOie",
      "Invoice Receivable Evidence Verified": "fldqrtHa31vyiylyT",
      "Remaining Client Receivable": "fldVcBACwlXVcm4iq",
      "Invoice Delivery Gate": "fldNNGkrqnuZMbBLe",
      "Invoice Receivable Gate": "flddMoES9nrs7Rars",
      "Historical Number Collision Verified": "fldtcRWgaMQSS5FBc",
      "Invoice Identity Integrity Gate": "fldCwLUolBZjams3R",
      "Client Invoice Continuity Review Status": "fldHaqnqFycph5iw1",
      "Prior Client Invoice Reference Snapshot": "fldaHNXSdj7lRbRzU",
      "Client Invoice Continuity Review Notes": "fldHkh7INaEBTocBq",
      "Invoice Continuity Review Gate": "fld1yra0cg9wCUFaF",
      "Mixed-Rate Staffing Calculation": "fldJSC9H9rY9GLM7o",
      "Mixed-Rate Staffing Amount": "fldH3jhMffmQdPidG",
      "Mixed-Rate Calculation Basis": "fld3rUKYBlj1lXBTd",
      "Mixed-Rate Correction Evidence": "fld13Xz9iexsVIYLL"
    }
  },
  "finance": {
    "id": "tblsy5wOMyg81ZWPE",
    "fields": {
      "Finance Item": "fldX9etpuYNpcYGXR",
      "Finance Area": "fldisohdVjoVVGBDM",
      "Related Client": "fldLFBYFEndMpZRBM",
      "Related Invoice": "fldgPAPfKleYbgwLY",
      "Related Payroll": "fldJfKkch7ASUp2es",
      "Amount": "fldJPYSfQ76F3b6vr",
      "Approval Status": "fldWx3RBBjcnUHaV6",
      "Notes": "flduit2U7iTrAeNlC",
      "Invoice Record": "fld78OCkPQWLmOpgc",
      "Payroll Cycle Records": "fldawrzyOAh52KGmG",
      "Invoice Amount": "fldm3F4sEmvJIbLA8",
      "Payroll Amount": "fldYP16TiIBQRck2n",
      "Calculated Spread": "fldzvcUPQTnf3tfhn",
      "Spread Variance": "fldaf2QMhRDI0YCC2",
      "Reconciliation Close Gate": "fldOGNNOptnTnNASy",
      "Client Record": "fldxNiz6SuYGrrcDs",
      "Evidence Records": "fldIiw0evfKotSLEC",
      "Command Ledger Records": "fldNdDYkdFVPYcIIb",
      "Result Check Records": "fldNFtJfJP0GThv6h",
      "Correction Records": "fldxxBRr1onKB5bvo",
      "State Transition Records": "fldpMRoRVyVgNRM9d",
      "Archive Records": "fldf6aVQ1wDoygdNN",
      "Coverage Requests": "fldOMrzaLb7MHbUE1",
      "Record Environment": "fldMFM8JWUHFYabTt",
      "Closeout Coverage Record ID Snapshot": "fldZ1eqXkuBWEEs77",
      "Closeout Case Key": "fldNLzpcWNAcckgKx",
      "Operational Completion Verified": "fldHaszY86jMod7l4",
      "Worker Liability Status": "fldY9qNn9yYHrpyuN",
      "Client Receivable Status": "fld0aZcJTBOSCZp6E",
      "Worker Payment Evidence Verified": "flde6Nb5caiFWNEle",
      "Client Payment Evidence Verified": "fldg0QsmDNT8ttHTc",
      "Reconciliation Exception Class": "fldx28GGKeVjFOIS7",
      "Closeout Disposition": "fldZ9DrMGg4l5fNB5",
      "End-to-End Closeout Gate": "fldvzys5X8qr2xKkE",
      "Payroll Finance Handoff Snapshot": "fld1v7W3sRgSl8MEC",
      "Payroll Remaining Liability Snapshot": "fldFREAqHQZOPCrLA",
      "Invoice Receivable Gate Snapshot": "fldtZvWEAhqN3ktZu",
      "Invoice Remaining Receivable Snapshot": "fld21SNH0mgwOWDdS",
      "Settlement Source Verification Gate": "fldwKUE3nY2uLrUkt",
      "Payroll Settlement Outcome Snapshot": "fldQrA7o8xnWYcV38",
      "Invoice Receivable Outcome Snapshot": "fldRRCv126Oqd5a72",
      "S11 Finance Operator State": "fldDPX7aBj9F3onQq",
      "S11 Finance Operator Action": "fldOwlmYTXdOMIRBd"
    }
  },
  "workers": {
    "id": "tbloSqRveT39fOF3K",
    "fields": {
      "Worker": "fldaPcpaeZBb86RFE",
      "Phone": "fldBVwB7uiBVPpUFd",
      "Email": "fldDtBFEyiOUo7rGq",
      "Worker Lifecycle State": "fldMpC3jSVbO6gQdt",
      "Current Client — Display Only": "fld2xGRLKrT9Adj1l",
      "Primary Role": "fldl11AXqP6UBMlnm",
      "Default Pay Rate — Reference Only": "fldpjgbEkPE8OiGKL",
      "Hours Capture Method Status": "flddldLYlKLgPKlz6",
      "Readiness Notes (Optional)": "fldqUg32FQuYhKS30",
      "Notes": "fldaawaEgHQTYAOHS",
      "Object ID": "fldZhDhI33RMt1MRF",
      "Client Record": "fldsy4MNwSNyoACe4",
      "LEGACY — Payroll Cycle Records — DO NOT USE": "fldPbBPJJJ6d2acVN",
      "Assigned Coverage Requests": "fldUcwKpYaAFhUGuQ",
      "Payroll Cycles": "fld69s43CqqwzoXF2",
      "Source Candidate Record": "fld2MbtGJrwosuAHH",
      "Backup Coverage Requests": "flduKKIYNysFjyZdS",
      "Original Assignment History": "fld7BYTsmkE6b7IT3",
      "Replacement Coverage Requests": "fldrGhEu9GSWFZs1M",
      "Worker Activation Date": "fldvL8GeC8jYFLST9",
      "Identity Verification Status": "fldVv0iLT6uZ1Ywla",
      "Work Authorization Verification Status": "fldm8a74AJ24as1fz",
      "Work Authorization Expiration Date": "fldaGnpUE4F7V53VR",
      "Onboarding Documentation Status": "fldedoI61bAYU2Uow",
      "Payment Method Status": "fld0Ckyo9jCxxd4a9",
      "Availability Status": "fldxnD2rCGgQgVMGF",
      "Availability Last Confirmed": "fldtJScMFzO7y1XSR",
      "Availability Summary": "fldZxVGvROzxPleQG",
      "Communication Status": "fld1iRR9FQBBVT88n",
      "Preferred Contact Channel": "fld9mQZJWqkraEcEZ",
      "Evidence Records": "fldKFxAhuVJYzEvDh",
      "Inactivation Date": "fldeN61TVgJG8foQ2",
      "Inactivation Reason": "fld5jcSwjnd4gDxcP",
      "Rehire Eligibility": "fldCndH2Im3DyPrjJ",
      "Screening Evidence Records": "fldgKV0ocYoZdn5qC",
      "Airtable Record ID — Immutable": "fldyy5fGU8l1TGMIE",
      "Source Candidate Activation Verified At": "fldzZV9JamoG2qrYX",
      "Record Environment": "fldSifBESW7FnD7j7",
      "Email Intake": "fldC7xSetYXzlGuKd",
      "Worker Bookings": "fldD8BSqe3TP05FST",
      "Team Member Number": "fldrbxSujwG2ieiad",
      "Birthday": "fldiODEUos4H5APbp"
    }
  },
  "bookings": {
    "id": "tblMW0700unQNa8A9",
    "fields": {
      "Booking ID": "fldExy9ifHvSSZu25",
      "Coverage Slot": "fldvUfAFH6CK4QvAL",
      "Worker": "fldRGABzpyw0Xcp13",
      "Matching Source": "fld8H2S0D9pO4uFSn",
      "Booking Sequence": "fldm0vawUX2aRogx3",
      "Booking Type": "fldb0ypKwsiipgiJ0",
      "Booking Status": "fldv4qVIrcfoSnkKJ",
      "Role Snapshot": "fld5uOaaFoAW3tnwO",
      "Scheduled Start Snapshot": "fld8fNP7ZSW6SjUXd",
      "Scheduled End Snapshot": "fldYpTYBd0QuHQyL3",
      "Worker Rate Snapshot": "fldhHvVIh7XlrJud7",
      "Client Rate Snapshot": "fldxnH2kzZkXrEFmv",
      "Offered At": "fldah9meLeo9piMcs",
      "Confirmed At": "fldHZEkXXssxDiJg7",
      "Released / Replaced At": "fld4urY4SHhPBaYBt",
      "Release / Replacement Reason": "fld0KUEcxVTihView",
      "Evidence Records": "fldJVsDYP6iUdaNSy",
      "Notes": "fldWqARv6RLhczV9D",
      "Replaces Booking": "fldDeeQZHHx1aRmYi",
      "From field: Replaces Booking": "fldJYkkZRSKR9R4dO",
      "Record Environment": "fldXAcVnAecrP8K1o",
      "Coverage Requests": "fldb9abV2clYm3P8i",
      "Candidate": "fldi0uwHYrtcDmHR0",
      "Homebase Assignment Evidence": "fldPvN4CwWkL53t9S"
    }
  }
};

