export const schema = {
  "intake": {
    "id": "tbl9Phdpg1UUZ6Lt6",
    "fields": {
      "Request ID": "fldAw9pG5AqAqGZdu",
      "Client Name": "fldgVCZnbblanvnaT",
      "Contact Name": "fldiZ7ID2wbB8fteP",
      "Phone": "fld6KwGrZXpuu3zSK",
      "Email": "fldP5lh6OE3hR4HVm",
      "Service Needed": "fld9bnkAELOLaO0pF",
      "Intake Status": "fldmLOna24pwBwNKE",
      "Notes": "fldzQLKMqpcZp91JJ",
      "Leads": "fldHeNV5rGoyUgbaG",
      "Intake Contact Route": "fldE5ToqHAvuq9c4m",
      "LEGACY — Intake Completeness Gate — DO NOT USE FOR CLI-01A": "fldJ3rLMM7864EljV",
      "Intake Match Key": "fld3Gy3v7NNla5lJ8",
      "Converted Client": "fldGy4HktY3H1YTYj",
      "Requested Location": "fldbyv8cHCU3k4QPM",
      "Urgency": "fldaWDLim3tOeC9GO",
      "Commercial Requirement": "fldviwrHSV9v5rBPd",
      "Intake Approval Status": "fld2eC2u3AlwpfFuk",
      "Evidence Records": "fldqSq2631WrX8gCg",
      "LEGACY — Conversion Integrity Gate — DO NOT USE FOR CLI-01A": "fldlv3Zt7cihiyHgf",
      "Source Update Inbox": "fldWGBGfutETLw7Rx",
      "Source Form Code": "fldB46JTgrp1mTO0f",
      "Source Form Version": "fldaJOfuKfEOzDrt4",
      "Source Submission ID": "fldYJhEVt2qkhyL39",
      "Source Gmail Thread ID": "fldfwRnOzKvs9aggJ",
      "Campaign Runs": "fldil2RBVEfwHUEFJ",
      "Intake Source Channel": "fldWKpc5wxseOz0VU",
      "Source Trace Gate": "fldahQhyZgtynuOc8",
      "Outreach Activity": "fldciotcZ7m7L8Wfg",
      "Task Records": "fldkwzj57ja8SO7kU",
      "Result Check Records": "fldZGXx4N1AcFKn8l",
      "Correction Records": "fldPHpfgBXFbjOitp",
      "Proposal Status": "fldTRYIdKzMbDisaj",
      "Proposal Evidence Records": "fld7a1ZoEauwcDjVu",
      "Coverage Requests": "fld3BYP4U4QoKIX1O",
      "Candidates": "fldhnPIWqEERPBtRc",
      "Tracked Staffing Request Link": "fld22hK1nmvZyvDFN",
      "Worker Matching Runs": "fldxnoqcEMf1LGiAd",
      "Worker Opportunity Matches": "fldBY5wMIDbb353EE",
      "Record Environment": "fldFzyliPzVtHBm6N",
      "Email Intake": "fldexmMORJACLaUSA",
      "Archive Closed Records": "fldbes5INIB7PYES5",
      "Source System": "fldkXPEfrqVxF5aLz",
      "Source Event ID": "fldIzTpc8N8v9OZHO",
      "Source Event Timestamp": "fldYKFzUHMObq6zMv",
      "Source Form ID": "fldqiq2uPt4Dxq7p2",
      "Source Event Key — Immutable": "fldc5mAVWf5V43Atj",
      "Reconciled / Ingested At": "fld5oTETsLn1A1RF8",
      "Client Identity Reconciliation": "fldguNODB5owub2kh",
      "Client Identity Reconciliation Basis": "fldnaPpz6LbTSgEHB",
      "Decision / Contact Authority Status": "fldxbHzibOkX1mGfd",
      "Client Readiness State": "fldg02jo5YPWDco5A",
      "Client Readiness Blockers": "fldQvTrYiU3rDSitn",
      "Service Authorization Decision": "fldE3JDMrLfNREu5m",
      "Proposal Control Status": "fldvRtzXdDNPXDFUb",
      "Rate Card Control Status": "fldUXwKyXPv9HQvso",
      "Agreement Control Status": "fldhNrIBSF7g9mIGs",
      "Insurance / Compliance / Onboarding Control Status": "fldq6XuS77WTHrGvC",
      "Expected Source Event Key": "fldHVef2ENljUOEoe",
      "CLI-01A Source Identity Gate": "fldKOZmOnAA0ou0rL",
      "Client Request Identity Key": "fldlOMchPHlhHxpTX",
      "CLI-01A Commercial / Service Authorization Gate": "fldW7Mgmccgyy26iN",
      "Rate Card Evidence Records": "fldCPvSrEgpY115JV",
      "Commercial Authority Snapshot": "fldIUZcqR1VYnUDk1",
      "CLI-02A Commercial Authority Gate": "fldiYWv8XBmkDIiNY"
    }
  },
  "clients": {
    "id": "tblQFZrTdguo4tIHD",
    "fields": {
      "Client Name": "fldN3AswQFwkYKU6m",
      "Main Contact": "fldJOLZUDwABoRG6R",
      "Phone": "fldgHqdWqrFdV7Ea5",
      "Email": "fldtFenqpID8clZPd",
      "Location": "fldK5QmvYVMHu6ubl",
      "Client Status": "fldI2DeMMzjQlkqO9",
      "Billing Rule": "fldmO8W5MiEhmsBlG",
      "Notes": "fldBKWisEpnSp5uDO",
      "NEXT State": "fldlFG6rGWmQtsyAE",
      "Client Gate Status": "fldiXWZ81Kf2fUL5T",
      "Risk Class": "fldOHzxSik31d6lWJ",
      "Payment Rhythm": "fldamYcJ9pnTiBvhJ",
      "Client Missing Info": "fldH6Zl4G3enteIMF",
      "Next Task": "fldXYB33dpIWyPkvT",
      "NEXT Object ID": "fldLwpS8WahWp04Ar",
      "Workers": "fldJt3IZALddBqCaD",
      "Coverage Requests": "fldeSfcuqX7B67aNt",
      "Payroll Cycles": "fldAHHzGvZ95nWBFG",
      "Tasks": "fld3ZxRNDu7lJxaTd",
      "Leads": "fldzluUHtINGa3JYf",
      "Client Intake": "fld4Bak0qOX4LH9P9",
      "Client Operations Gate": "flduF4YmX5QE8BT1c",
      "Candidates": "fldU7NzuIIv2FEahJ",
      "Invoices": "fldxUYYZJmsSZVmV5",
      "Finance Control": "fldmXptHgtWwXWZ1j",
      "Evidence Records": "fldbuj7BBCKxLpkXl",
      "Command Ledger Records": "fldNDbmnigleEOAs8",
      "Result Check Records": "fldnMHCKNJdHl58wP",
      "Correction Records": "fld7t1wLzCHRexBgX",
      "State Transition Records": "fldGxeaFU9cpqwZji",
      "Archive Records": "fldXi8f89ybVX0xQg",
      "Commercial Agreement Status": "flduEP2biJHvjroOf",
      "Current Agreement Evidence": "fldt8nLnjC9W10AFB",
      "Agreement Effective Date": "fldU2aB2eWCteZGQR",
      "Record Environment": "fldcHSztAFzgujbDe",
      "Email Intake": "fldBocZYmtthyeL6F",
      "Client-Facing Packet Status": "fldEpAxPix3MTaAt1",
      "Proposal Evidence Records": "fld7BxgfdSEOOl6eY",
      "Agreement History Evidence": "fldPYc8XcrYIpxcfr",
      "Client Packet Version": "fldnF4YAj332BfFRN",
      "Client Packet Missing Items": "fldQRgoVXBJrlUWpH",
      "Client Packet Last Reviewed At": "fld2yim8ghoHS1W08",
      "Client Packet Recovery Owner": "fld7jBtqvgom6U9AJ",
      "Client Packet Classification": "fldl3K7kAZefYYnkN",
      "Client-Facing Packet Gate": "fldFL88gUpKIn6HJa",
      "Rate Card Evidence Records": "fldpqcZqOYKPWnnlY"
    }
  },
  "evidence": {
    "id": "tblmeZC1GiM0R6VhK",
    "fields": {
      "Evidence ID": "fldCm0NrZjlJFrhZ1",
      "Evidence Type": "fldMOajIMwnTAt3Sw",
      "Legacy Related Module": "fldWz53xYTLhQ6m20",
      "Related Object": "fldFkO84Hr6fbndvx",
      "Evidence Date": "fldPUQBkypb16HduT",
      "File Link": "fld9c6v4F3XAbBw4v",
      "Attachment": "fldw1m82KDAxmC4Rn",
      "Verified": "fldh4zz4zXEykfeHP",
      "Notes": "fldGhg5mEfNLXNbc9",
      "Related Object ID": "fld08tPrftDVrXV9b",
      "Candidates": "fldUOJz51Z3KAIaxF",
      "Related Module": "fld28RV2apjOW9fy1",
      "Related Module Registry": "fldKnImVgmCP0X5Em",
      "Evidence Integrity Gate": "fldsHUcMXgXY809T1",
      "Corrections / Verification": "fld2ZTfcSCBvYwUyU",
      "Workers": "fldEs0wbruA8Oa4vk",
      "Client Intake": "fldgphuRy1uqbI5SF",
      "Coverage Requests": "fldN53GEQ8GkEZdjp",
      "Payroll Cycles": "fldieDGRpqWa5kGvl",
      "Invoices": "fldCkVl3heURcnqeM",
      "Finance Control": "fld6ZGruMTEsC0Gdk",
      "Clients": "fldbbs1kBQ2IkDfwX",
      "Leads": "fldDr2XGVJkHcAtHR",
      "Content OS": "fldMrFSBYTTy3DDcC",
      "Outreach Activity": "fldDLNWeslulntnuc",
      "Suppression Registry": "fldlZ5tG9nqoL4xNt",
      "LEGACY — Client Intake Reciprocal — DO NOT USE": "fldf3CWQKdnfgrAhZ",
      "LEGACY — Clients Reciprocal — DO NOT USE": "fldCkJb4XQKQRuBhm",
      "Worker Profile Items": "fldLl2J419Ys4XJdf",
      "Worker Matching Runs": "fldLf5NXdxJO7jXyS",
      "Worker Opportunity Matches": "fldOmNh1mJrS6FYhO",
      "LEGACY — Workers 2 — DO NOT USE": "fld3aGT6UtUMt1w3W",
      "Record Environment": "fldeFEgrNX0koST1A",
      "Alarms": "fldlv7gASWLy2EwG8",
      "State Transitions": "fldsJmllAJttjWWly",
      "Email Intake": "fldJHFX65iMGpSGoS",
      "Worker Bookings": "fldqQ1lS2ztFOxLww",
      "Register Registry": "fldpAfUqp9dEPeB1z",
      "Automation & Integration Manifest": "fldu0YCJX0vIlmzXT",
      "Source Provenance Verified": "fld9oiNlaqgIg4vAa",
      "Provenance Disposition": "fldE1Kj8pRbm20tPu",
      "Performance Review": "fldGTYqiSZmNNwzJR",
      "Clients 2": "fldjDSZ4eQWC22N35",
      "Clients 3": "flduwuNrch2C1n2Hb",
      "Content Specifications Registry": "flda9L2jDhe4cvgIt",
      "Build Roadmap": "fldg7Jxv6HIqKIVrR",
      "Archive Closed Records": "fldf1NxDKHNhG1myF",
      "Invoices 2": "fldRGzYGnNtApbLNv",
      "Candidate Profiles": "fldFMMEXyzgv5BRHj",
      "Candidate Profile Items": "fldoI5BdkTdybjdax",
      "Candidate Professional Experience": "fldEBo2bkoRT90DdU",
      "Candidate CV Artifacts": "fldSlGdu7vH0XKDIv",
      "Client Intake 2": "fldFz6u9ERaBDtyA7",
      "Clients 4": "fldKB3nBkRw9bhhpV",
      "Candidate Profiles 2": "fldkjaPuAc9eav5Hl",
      "Worker Bookings 2": "fldvejwRo9mYsync8"
    }
  },
  "candidates": {
    "id": "tblwNK4Eh45g211IO",
    "fields": {
      "Candidate": "fldJKCZuPhh3UtjTb",
      "Phone": "fldCecINc4FpCSqET",
      "Email": "fldoKKCwO7Ivxe7kP",
      "Target Role": "fld3SG0J0sGzd5HV5",
      "Location": "fldQVaLnDOVXHODxB",
      "Availability": "fldqkIkEM2qf5PCbB",
      "English Level": "fldovwr18NH5DneZ9",
      "Source": "fldhIELgzwPy9qgAA",
      "Missing Pieces": "fldXt0tEjbw9617gn",
      "Client Ready Summary": "fldfPZWdZnWio42Re",
      "Evidence Link": "fldepe0PMEuRb9dvt",
      "Notes": "fldPrNUkWEGH4jjT8",
      "Object ID": "fldCtdzsclgoN98Dl",
      "Promoted Worker": "fldVyYzb5zhvOVDNG",
      "Work Authorization Classification": "fldGLCkN7TJshbE25",
      "Shortlist Status": "fldDWqN801cMDywdD",
      "Follow-up Status": "fld6KBF8dG9lbEIJ2",
      "Next Follow-up Date": "fld3ghOIFSclCRoNA",
      "Evidence Records": "fldVUZsiJmgEQjbuT",
      "Potential Client Matches": "fldZNLShk9JP5OrVl",
      "Transportation Status": "fldErNWRZYgKzH6Da",
      "Resume Processing Status": "fld4YGiqsmeNZDvLv",
      "Candidate Agreement Status": "fldV8ST8Lgx2U1J2k",
      "Source Client Intake Requests": "fldcFbiEC4TgBINRQ",
      "Tracked Representation Agreement Link": "fldEJ3BcDE5gpynqh",
      "Airtable Record ID — Immutable": "fldlcll6jAlQPLTiG",
      "Record Environment": "fldpneHwAozzSqhHU",
      "Email Intake": "fldbWJ8W8OCCkMSu8",
      "Candidate Profile Submission ID": "fldv6uhlTC7hxdIei",
      "Candidate Profile Edit Link": "fldOS64lne1otPqSt",
      "Administrative Reconstruction Submission ID": "fldoeI5LU7xfB70ic",
      "Agreement Initial Sent At": "fldZnAQh0joObdkF4",
      "Agreement R1 Sent At": "fldswSVdeg85ll6cO",
      "Agreement R2 Sent At": "fldF1i1XpB4EhNh5z",
      "TM Issuance Sequence": "fldGyELrjYdMImZ31",
      "Team Member Number": "fldnHkyYsMHhPuCeF",
      "Identity Reconciliation Status": "fld5TPtZlMgfIsStX",
      "Identity Reconciliation Basis": "fldJZbj78mRMJqGYZ",
      "Population Reconciliation Disposition": "fldPVz6tt7zWwageF",
      "Canonical Candidate Record": "fldYOrKNzFKiLNUXj",
      "From field: Canonical Candidate Record": "fldXGXSPcbxlkfq24",
      "Population Reconciliation Effective Disposition": "flduBnolckEq07tNX",
      "Identity Reconciliation Effective Status": "fldniFrpXvMnw6ZkU",
      "Candidate Profile Items": "fldz1FojZjUmkBGwk",
      "Candidate Professional Experience": "fldDB2PHknlnXfkkR",
      "Candidate CV Artifacts": "flduUjlWQ19boBZG3",
      "Bench Positions": "fld4TfSEu0BXXw56i",
      "Bench Narrow Classifications": "fldFjG5idYvHNZIO8",
      "Bench Availability Status": "fldHD2g0gaqLOZ85w",
      "Bench Availability Verified At": "fld4fNk9jVYo1S1Wu",
      "Email Verification Status": "fldQSwsRzoNoXnAsh",
      "Email Verified At": "fldVVRoB4ObHG48ST",
      "Worker Bookings": "fld44zhnOqscvdBTI",
      "Preferred Work Areas": "fldIwkb2oxGtsN7q6"
    }
  },
  "leads": {
    "id": "tblaCk5tyADLKIuwv",
    "fields": {
      "Lead ID": "fldlDDtYe3AcX0QJO",
      "Business": "fldONiL6lC1QUiAwI",
      "Emails": "fldwLPuEpmUuLkL9B",
      "Phone": "fldVPzIXdqh1Oxdrh",
      "Client Record": "fldaoHawxNkV7KrbI",
      "Evidence Records": "fld0SXPon7hJbhHU9"
    }
  }
};
