import test from 'node:test';import assert from 'node:assert/strict';
import {FakeBase} from './harness.mjs';import {fillMissingStaffingSlots} from '../../automation/intake/coverage-slots.mjs';import {prepareFinanceDrafts} from '../../automation/intake/finance-drafts.mjs';
const ctx={qa:true,exclusiveClaim:async()=>true};
import {runIntakeHandoffs} from '../../automation/intake/handoff-runner.mjs';
test('existing Client claim runs exact sourced slot and verified financial handoffs, with replay reuse',async()=>{
 const f=await completed(),e={lane:'client',qa:true},r={status:'done',recordIds:[f.evidenceId]};
 const first=await runIntakeHandoffs(e,r,f.b,async()=>true);
 assert.equal(first.slots.created.length,0);assert.equal(first.slots.reused.length,2);
 assert.equal(first.finance[0].disposition,'DRAFTS_PREPARED');
 const replay=await runIntakeHandoffs(e,r,f.b,async()=>true);assert.deepEqual(replay,first);
 for(const t of ['payroll','invoices','finance'])assert.equal(f.b.data[t].size,1);
 assert.equal((await runIntakeHandoffs(e,r,f.b,async()=>false)).reason,'EXCLUSIVE_NATIVE_CLAIM_REQUIRED');
});
function fixture(){const b=new FakeBase(),clientId=b.seed('clients',{'Client Name':'[JEF INTAKE QA] Client'}),workerId=b.seed('workers',{'Worker':'TEST-Worker'}),requestId=b.seed('intake',{'Request ID':'TEST-REQUEST','Converted Client':[{id:clientId}],'CLI-01A Commercial / Service Authorization Gate':'PASS — SERVICE REQUEST AUTHORIZED / STOP BEFORE COVERAGE'}),headerId=b.seed('coverage',{'Coverage Request':'TEST-Demand','Coverage Record Type':{name:'Demand Header'},'Client Record':[{id:clientId}],'Source Client Intake':[{id:requestId}],'Required Headcount':2,'Source Event ID':'TEST-EVENT',Role:'Barista','Shift Date':'2026-10-01','Start Time':'2026-10-01T11:00:00Z','End Time':'2026-10-01T23:00:00Z',Location:'QA Venue','Assignment Sequence':1,'Shift Block Sequence':1}),evidenceId=b.seed('evidence',{'Evidence ID':'TEST-EVIDENCE',Verified:true,'Source Provenance Verified':true,'Provenance Disposition':{name:'Accepted Source'},'Coverage Requests':[{id:headerId}],'Client Intake':[{id:requestId}]});b.data.coverage.get(headerId)['Evidence Records']=[{id:evidenceId}];return{b,clientId,workerId,requestId,headerId,evidenceId};}
async function completed(){const f=fixture();const r=await fillMissingStaffingSlots(f.requestId,f.b,ctx),coverageId=r.created[0],c=f.b.data.coverage.get(coverageId);Object.assign(c,{'Worker Records':[{id:f.workerId}],'Attendance Outcome':{name:'Completed'},'Verified Hours':11.5,'Hours Evidence Verified':true,'Time Verification Status':{name:'Verified'},'Approved Worker Rate Snapshot':20,'Approved Client Rate Snapshot':30,'Rate Evidence Status':{name:'Verified'}});f.b.data.evidence.get(f.evidenceId)['Coverage Requests'].push({id:coverageId});return{...f,coverageId};}
test('P2 creates only missing slots and replay reuses exact slots without bookings/workers',async()=>{const f=fixture(),r=await fillMissingStaffingSlots(f.requestId,f.b,ctx);assert.equal(r.disposition,'SLOTS_RECONCILED');assert.equal(r.created.length,2);const replay=await fillMissingStaffingSlots(f.requestId,f.b,ctx);assert.equal(replay.created.length,0);assert.deepEqual(replay.reused,r.created);assert.equal(f.b.data.coverage.size,3);assert.equal(f.b.data.bookings.size,0);assert.equal(f.b.data.workers.size,1);});
for(const [name,edit,reason]of [['Authorized alone',f=>f.b.data.intake.get(f.requestId)['CLI-01A Commercial / Service Authorization Gate']='BLOCKED','FULL_COMMERCIAL_GATE_REQUIRED'],['no source',f=>f.b.data.coverage.get(f.headerId)['Evidence Records']=[],'REVIEWED_DEMAND_EVIDENCE_REQUIRED'],['unreviewed source',f=>f.b.data.evidence.get(f.evidenceId).Verified=false,'REVIEWED_DEMAND_EVIDENCE_REQUIRED'],['missing schedule',f=>f.b.data.coverage.get(f.headerId)['End Time']=null,'INCOMPLETE_OR_CONFLICTING_DEMAND_FACTS'],['fractional headcount',f=>f.b.data.coverage.get(f.headerId)['Required Headcount']=2.5,'INCOMPLETE_OR_CONFLICTING_DEMAND_FACTS']])test('P2 '+name+' holds without creating demand/slots',async()=>{const f=fixture();edit(f);const r=await fillMissingStaffingSlots(f.requestId,f.b,ctx);assert.equal(r.reason,reason);assert.equal(f.b.data.coverage.size,1);});
test('P2 source header absent does not derive facts from free text',async()=>{const f=fixture();f.b.data.coverage.delete(f.headerId);assert.equal((await fillMissingStaffingSlots(f.requestId,f.b,ctx)).reason,'SOURCED_DEMAND_HEADER_REQUIRED');assert.equal(f.b.data.coverage.size,0);});
test('P2 existing conflicting slot blocks; reduced headcount never deletes prior slots',async()=>{const f=fixture();const r=await fillMissingStaffingSlots(f.requestId,f.b,ctx);f.b.data.coverage.get(f.headerId)['Required Headcount']=1;assert.equal((await fillMissingStaffingSlots(f.requestId,f.b,ctx)).disposition,'SLOTS_RECONCILED');assert.equal(f.b.data.coverage.size,3);f.b.data.coverage.get(r.created[0]).Role='Changed';assert.equal((await fillMissingStaffingSlots(f.requestId,f.b,ctx)).reason,'EXISTING_SLOT_CONTRADICTION');});
test('P3 single exact verified slot creates drafts and reciprocal links; replay reuses all money objects',async()=>{const f=await completed(),r=await prepareFinanceDrafts(f.coverageId,f.b,ctx);assert.equal(r.disposition,'DRAFTS_PREPARED');const p=f.b.data.payroll.get(r.payrollId),i=f.b.data.invoices.get(r.invoiceId);assert.equal(p.Hours,11.5);assert.equal(p['Gross Pay'],230);assert.equal(p['Coverage Record ID Snapshot'],f.coverageId);assert.equal(i['Total Amount'],345);assert.equal(i['Invoice Status'].name,'Draft');assert.equal(p['Payment Authorized'],undefined);assert.equal(i['Send Authorized'],undefined);assert.equal(f.b.data.finance.get(r.financeId)['Operational Completion Verified'],undefined);const replay=await prepareFinanceDrafts(f.coverageId,f.b,ctx);assert.deepEqual(replay,r);for(const t of ['payroll','invoices','finance'])assert.equal(f.b.data[t].size,1);});
for(const[name,edit]of [['projected hours',f=>f.b.data.coverage.get(f.coverageId)['Verified Hours']=null],['disputed time',f=>f.b.data.coverage.get(f.coverageId)['Time Verification Status']={name:'Disputed'}],['unreviewed Evidence',f=>f.b.data.evidence.get(f.evidenceId).Verified=false],['wrong source link',f=>f.b.data.evidence.get(f.evidenceId)['Coverage Requests']=[]],['unapproved rates',f=>f.b.data.coverage.get(f.coverageId)['Rate Evidence Status']={name:'Missing'}]])test('P3 '+name+' never creates money objects',async()=>{const f=await completed();edit(f);assert.equal((await prepareFinanceDrafts(f.coverageId,f.b,ctx)).disposition,'HOLD');for(const t of ['payroll','invoices','finance'])assert.equal(f.b.data[t].size,0);});
test('P3 preserves existing aggregate payroll like SIBOS instead of duplicating or distributing hours',async()=>{const f=await completed(),id=f.b.seed('payroll',{'Payroll Cycle':'TEST-Existing aggregate','Workers':[{id:f.workerId}],'Client Record':[{id:f.clientId}],'Period Start':'2026-09-28','Period End':'2026-10-01',Hours:46.5,'Gross Pay':930});assert.equal((await prepareFinanceDrafts(f.coverageId,f.b,ctx)).reason,'EXISTING_PERIOD_AGGREGATE_REQUIRES_RECONCILIATION');assert.equal(f.b.data.payroll.size,1);assert.equal(f.b.data.payroll.get(id).Hours,46.5);assert.equal(f.b.data.invoices.size,0);});
test('P3 partial write failure recovers same payroll on replay',async()=>{const f=await completed();f.b.failNext='invoices:create';await assert.rejects(prepareFinanceDrafts(f.coverageId,f.b,ctx));assert.equal(f.b.data.payroll.size,1);assert.equal((await prepareFinanceDrafts(f.coverageId,f.b,ctx)).disposition,'DRAFTS_PREPARED');for(const t of ['payroll','invoices','finance'])assert.equal(f.b.data[t].size,1);});
test('P2/P3 cannot write without claim or across production/QA boundary',async()=>{const f=await completed();for(const fn of [()=>fillMissingStaffingSlots(f.requestId,f.b,{}),()=>prepareFinanceDrafts(f.coverageId,f.b,{})])assert.equal((await fn()).reason,'EXCLUSIVE_NATIVE_CLAIM_REQUIRED');assert.equal((await fillMissingStaffingSlots(f.requestId,f.b,{exclusiveClaim:async()=>true})).reason,'FULL_COMMERCIAL_GATE_REQUIRED');assert.equal((await prepareFinanceDrafts(f.coverageId,f.b,{exclusiveClaim:async()=>true})).reason,'ENVIRONMENT_MISMATCH');});
test('P2 lost exclusive claim prevents any slot effect',async()=>{const f=fixture();let checks=0;const r=await fillMissingStaffingSlots(f.requestId,f.b,{qa:true,exclusiveClaim:async()=>++checks===1});assert.equal(r.reason,'EXCLUSIVE_CLAIM_LOST');assert.equal(f.b.data.coverage.size,1);});
test('P2 source approval revoked after admission prevents the first slot write',async()=>{const f=fixture();let claims=0;const r=await fillMissingStaffingSlots(f.requestId,f.b,{...ctx,exclusiveClaim:async()=>{if(++claims===2)f.b.data.evidence.get(f.evidenceId).Verified=false;return true;}});assert.equal(r.reason,'SOURCE_EVIDENCE_CHANGED_BEFORE_WRITE');assert.equal(f.b.data.coverage.size,1);});
for(const [name,edit] of [
 ['assignment sequence',f=>f.b.data.coverage.get(f.headerId)['Assignment Sequence']=2],
 ['shift block',f=>f.b.data.coverage.get(f.headerId)['Shift Block Sequence']=2],
 ['source request',f=>f.b.data.coverage.get(f.headerId)['Source Client Intake']=[]],
 ['evidence identity',f=>f.b.data.coverage.get(f.headerId)['Evidence Records']=[]],
 ['environment',f=>f.b.data.coverage.get(f.headerId)['Record Environment']='Production / Live'],
])test('P2 changed '+name+' after admission prevents stale slot writes',async()=>{const f=fixture();let claims=0;const r=await fillMissingStaffingSlots(f.requestId,f.b,{...ctx,exclusiveClaim:async()=>{if(++claims===2)edit(f);return true;}});assert.equal(r.reason,'DEMAND_CHANGED_BEFORE_WRITE');assert.equal(f.b.data.coverage.size,1);});
test('P2 source revocation after a partial effect holds and recovery reuses the first slot',async()=>{const f=fixture();let claims=0;const r=await fillMissingStaffingSlots(f.requestId,f.b,{...ctx,exclusiveClaim:async()=>{if(++claims===3)f.b.data.evidence.get(f.evidenceId)['Source Provenance Verified']=false;return true;}});assert.equal(r.reason,'SOURCE_EVIDENCE_CHANGED_BEFORE_WRITE');assert.equal(r.created.length,1);assert.equal(f.b.data.coverage.size,2);f.b.data.evidence.get(f.evidenceId)['Source Provenance Verified']=true;const recovery=await fillMissingStaffingSlots(f.requestId,f.b,ctx);assert.deepEqual(recovery.reused,r.created);assert.equal(recovery.created.length,1);assert.equal(f.b.data.coverage.size,3);});
test('P3 future/endless shifts cannot create finance drafts',async()=>{const f=await completed();f.b.data.coverage.get(f.coverageId)['End Time']='2026-10-10T12:00:00Z';const r=await prepareFinanceDrafts(f.coverageId,f.b,{...ctx,now:()=> '2026-10-04T20:00:00Z'});assert.equal(r.reason,'SHIFT_NOT_EVIDENCED_AS_ENDED');assert.equal(f.b.data.payroll.size,0);});
test('P3 lost exclusive claim prevents any money effect',async()=>{const f=await completed();let reads=0;await assert.rejects(prepareFinanceDrafts(f.coverageId,f.b,{qa:true,exclusiveClaim:async()=>++reads===1}),/EXCLUSIVE_CLAIM_LOST/);assert.equal(f.b.data.payroll.size,0);});
test('P3 Paid historical object stays protected without state/amount changes',async()=>{const f=await completed();const r=await prepareFinanceDrafts(f.coverageId,f.b,ctx);const p=f.b.data.payroll.get(r.payrollId);p['Worker Payment Status']={name:'Paid'};const before=structuredClone(p);assert.equal((await prepareFinanceDrafts(f.coverageId,f.b,ctx)).reason,'PROTECTED_OR_CONFLICTING_MONEY_OBJECT');assert.deepEqual(p,before);});
test('P3 source Evidence revoked after plan stops before money effect',async()=>{const f=await completed();let claims=0;await assert.rejects(prepareFinanceDrafts(f.coverageId,f.b,{...ctx,exclusiveClaim:async()=>{if(++claims===2)f.b.data.evidence.get(f.evidenceId).Verified=false;return true;}}),/SOURCE_EVIDENCE_CHANGED_DURING_WRITE/);assert.equal(f.b.data.payroll.size,0);});
for(const [name,field,value] of [
 ['source content','Notes','Corrected actual time claim'],
 ['source URL','File Link','https://example.invalid/revised-time'],
 ['source attachment','Attachment',[{id:'attRevised',url:'https://example.invalid/revised'}]],
 ['source identity','Related Object ID','recOtherScope01'],
 ['person scope','Workers',[{id:'recOtherWorker1'}]],
])test('P3 '+name+' changed with approvals still true stops before first money effect',async()=>{
 const f=await completed();let claims=0;
 await assert.rejects(prepareFinanceDrafts(f.coverageId,f.b,{...ctx,exclusiveClaim:async()=>{if(++claims===2)f.b.data.evidence.get(f.evidenceId)[field]=value;return true;}}),/SOURCE_EVIDENCE_CHANGED_DURING_WRITE/);
 for(const t of ['payroll','invoices','finance'])assert.equal(f.b.data[t].size,0);
});
test('P3 source correction after payroll stops subsequent drafts and replay reuses payroll',async()=>{
 const f=await completed();let claims=0;
 await assert.rejects(prepareFinanceDrafts(f.coverageId,f.b,{...ctx,exclusiveClaim:async()=>{if(++claims===3)f.b.data.evidence.get(f.evidenceId).Notes='Reviewed correction';return true;}}),/SOURCE_EVIDENCE_CHANGED_DURING_WRITE/);
 assert.equal(f.b.data.payroll.size,1);assert.equal(f.b.data.invoices.size,0);
 const payrollId=[...f.b.data.payroll.keys()][0];const r=await prepareFinanceDrafts(f.coverageId,f.b,ctx);
 assert.equal(r.payrollId,payrollId);for(const t of ['payroll','invoices','finance'])assert.equal(f.b.data[t].size,1);
});
