import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeSubmission,normalizePhone,normalizeEmail } from '../../netlify/functions/_shared/intake-normalize.mts';
import { reconcile } from '../../automation/intake/reconcile.mjs';
import {FakeBase,source} from './harness.mjs';
const now='2026-09-27T04:30:00.000Z';
const env=(lane='candidate',id='9000000000000000001',overrides={})=>normalizeSubmission(lane,source(lane,id,overrides),now);
const first=(b,t)=>[...b.data[t].values()][0];
test('normalization separates home area and preferred markets; preserves explicit negatives',()=>{const e=env();assert.equal(e.person.email,'qa.alex@example.invalid');assert.equal(e.person.phone,'+12025550101');assert.equal(e.candidate.location,'Miami, FL');assert.equal(e.candidate.preferredAreas,'Broward; West Palm Beach');assert.equal(e.snapshot.answers['16'].value,'No');assert.equal(e.snapshot.answers['46'].value,'No, I do not consent');assert.equal(e.sourceTimestamp,null);});
test('no identity normalization strips email plus tags or invents international country codes',()=>{assert.equal(normalizeEmail('Alex+work@Example.org'),'alex+work@example.org');assert.equal(normalizePhone('+54 11 5555 1234'),'+541155551234');assert.equal(normalizePhone('541155551234'),'');});
test('provider numeric IDs are rejected to avoid lost precision',()=>{const s=source();s.id=Number(s.id);assert.throws(()=>normalizeSubmission('candidate',s,now),/INVALID_PROVIDER/);});
test('foreign form and deleted submissions are rejected',()=>{const s=source();s.form_id='1';assert.throws(()=>normalizeSubmission('candidate',s,now));s.form_id='261480775333056';s.status='DELETED';assert.throws(()=>normalizeSubmission('candidate',s,now));});
test('Candidate new path writes one person and linked source without readiness or activation',async()=>{const b=new FakeBase();const r=await reconcile(env(),b);assert.equal(r.status,'done');assert.equal(b.data.candidates.size,1);assert.equal(b.data.evidence.size,1);const c=first(b,'candidates');assert.equal(c['Record Environment'],'QA / Test');assert.equal(c['Candidate Profile Submission ID'],'9000000000000000001');assert.equal(c['Work Authorization Classification'],undefined);assert.equal(c['Promoted Worker'],undefined);assert.equal(c['Bench Availability Status'],undefined);assert.ok(first(b,'evidence').Candidates.length===1);});
test('Candidate replay reuses entity and source even when transport state is lost',async()=>{const b=new FakeBase();await reconcile(env(),b);await reconcile(env(),b);assert.equal(b.data.candidates.size,1);assert.equal(b.data.evidence.size,1);});
test('historical manual entry with normalized name and contact is reused',async()=>{const b=new FakeBase();const id=b.seed('candidates',{Candidate:'[JEF INTAKE QA] Alex Rivera',Email:'QA.ALEX@example.invalid',Phone:'202-555-0101','Object ID':'TEST-OLD','Target Role':'Bartender'});const r=await reconcile(env(),b);assert.equal(b.data.candidates.size,1);assert.equal(b.data.candidates.get(id)['Target Role'],'Bartender');assert.equal(b.data.candidates.get(id)['Candidate Profile Submission ID'],'9000000000000000001');assert.equal(r.status,'exception');});
test('existing source with a changed managed field updates while blank optional does not erase',async()=>{const b=new FakeBase();await reconcile(env(),b);const later=env('candidate','9000000000000000001',{34:'Server',8:{}});later.receivedAt='2026-09-28T04:30:00.000Z';await reconcile(later,b);assert.equal(b.data.candidates.size,1);assert.equal(first(b,'candidates')['Target Role'],'Server');assert.equal(first(b,'candidates').Location,'Miami, FL');assert.equal(b.data.evidence.size,2);});
test('owner improvement survives a later form change',async()=>{const b=new FakeBase();await reconcile(env(),b);first(b,'candidates')['Target Role']='Specialty Coffee / Barista';const r=await reconcile(env('candidate','9000000000000000001',{34:'Server'}),b);assert.equal(first(b,'candidates')['Target Role'],'Specialty Coffee / Barista');assert.equal(r.status,'exception');});
test('email and phone pointing to different people hold, with no new person',async()=>{const b=new FakeBase();b.seed('candidates',{Candidate:'[JEF INTAKE QA] Alex Rivera',Email:'qa.alex@example.invalid'});b.seed('candidates',{Candidate:'[JEF INTAKE QA] Other Person',Phone:'202-555-0101'});const r=await reconcile(env(),b);assert.equal(r.status,'exception');assert.equal(b.data.candidates.size,2);assert.equal(first(b,'evidence').Candidates,undefined);});
test('missing contact creates recoverable evidence only',async()=>{const b=new FakeBase();const r=await reconcile(env('candidate','9000000000000000001',{4:'',5:''}),b);assert.equal(r.status,'exception');assert.equal(b.data.candidates.size,0);assert.equal(b.data.evidence.size,1);});
test('new separate submission for same person does not replace master submission ID',async()=>{const b=new FakeBase();await reconcile(env(),b);await reconcile(env('candidate','9000000000000000002'),b);assert.equal(b.data.candidates.size,1);assert.equal(first(b,'candidates')['Candidate Profile Submission ID'],'9000000000000000001');assert.equal(first(b,'candidates')['Evidence Records'].length,2);});
test('unmapped language remains source text instead of invented level',async()=>{const b=new FakeBase();const r=await reconcile(env('candidate','9000000000000000001',{14:'Unexpected level'}),b);assert.equal(r.status,'exception');assert.equal(first(b,'candidates')['English Level'],undefined);assert.ok(first(b,'evidence').Notes.includes('Unexpected level'));});
test('resume references remain in source evidence and mark received only',async()=>{const b=new FakeBase();await reconcile(env('candidate','9000000000000000001',{27:['https://www.jotform.com/uploads/qa/cv.pdf']}),b);assert.equal(first(b,'candidates')['Resume Processing Status'].name,'Received Original');assert.ok(first(b,'evidence').Notes.includes('cv.pdf'));});
test('Client creates intake, distinct account and both evidence relationships',async()=>{const b=new FakeBase();const r=await reconcile(env('client'),b);assert.equal(r.status,'done');assert.equal(b.data.intake.size,1);assert.equal(b.data.clients.size,1);assert.equal(first(b,'clients')['Client Status'].name,'Lead');assert.equal(first(b,'clients').Location,undefined);assert.equal(first(b,'intake')['Requested Location'],'Miami Beach, FL');assert.equal(first(b,'intake')['Service Authorization Decision'].name,'Not Reviewed');assert.equal(first(b,'intake')['Converted Client'].length,1);assert.equal(first(b,'evidence').Clients.length,1);});
test('Client existing account reuses multi-email canonical contact and preserves main contact',async()=>{const b=new FakeBase();const id=b.seed('clients',{'Client Name':'[JEF INTAKE QA] River Events',Email:'billing@example.invalid; qa.alex@example.invalid','Main Contact':'Original account contact','Client Status':{name:'Active'}});await reconcile(env('client'),b);assert.equal(b.data.clients.size,1);assert.equal(b.data.clients.get(id)['Main Contact'],'Original account contact');assert.equal(b.data.clients.get(id).Email,'billing@example.invalid; qa.alex@example.invalid');});
test('Client repeated request reuses source and account without duplicating links',async()=>{const b=new FakeBase();await reconcile(env('client'),b);await reconcile(env('client'),b);assert.equal(b.data.clients.size,1);assert.equal(b.data.intake.size,1);assert.equal(b.data.evidence.size,1);assert.equal(first(b,'intake')['Evidence Records'].length,1);});
test('Client ambiguous account identity retains request, no manufactured account relationship',async()=>{const b=new FakeBase();b.seed('clients',{'Client Name':'[JEF INTAKE QA] River Events',Email:'other@example.invalid'});const r=await reconcile(env('client'),b);assert.equal(r.status,'exception');assert.equal(b.data.clients.size,1);assert.equal(first(b,'intake')['Converted Client'],undefined);});
test('Client unmapped service preserves exact request and flags mapping exception',async()=>{const b=new FakeBase();const r=await reconcile(env('client','9000000000000000001',{9:['Unexpected new service']}),b);assert.equal(r.status,'exception');assert.equal(first(b,'intake')['Service Needed'],undefined);assert.ok(first(b,'intake').Notes.includes('Unexpected new service'));});
test('partial failure after Evidence but before Candidate creation recovers by replay',async()=>{const b=new FakeBase();b.failNext='candidates:create';await assert.rejects(()=>reconcile(env(),b));assert.equal(b.data.evidence.size,1);await reconcile(env(),b);assert.equal(b.data.candidates.size,1);assert.equal(b.data.evidence.size,1);});
test('partial failure after Client Intake but before account creation recovers',async()=>{const b=new FakeBase();b.failNext='clients:create';await assert.rejects(()=>reconcile(env('client'),b));assert.equal(b.data.intake.size,1);await reconcile(env('client'),b);assert.equal(b.data.intake.size,1);assert.equal(b.data.clients.size,1);});
test('form version drift persists source and prevents entity writes',async()=>{const b=new FakeBase();const r=await reconcile(env('candidate','9000000000000000001',{50:'2.0'}),b);assert.equal(r.status,'exception');assert.equal(b.data.candidates.size,0);});
test('current Jotform services persist literally without legacy-category guesses',async()=>{
 for(const value of ['Temporary Staffing & Payroll Support','Trial-to-Hire','Direct Hire Recruiting']){
  const b=new FakeBase();const r=await reconcile(env('client','9000000000000000001',{9:[value]}),b);assert.equal(r.status,'done');assert.equal(first(b,'intake')['Service Needed'][0].name,value);
 }
});
test('explicit Not Sure remains unknown service intent',async()=>{const b=new FakeBase();const r=await reconcile(env('client','9000000000000000001',{9:['Not Sure']}),b);assert.equal(r.status,'exception');assert.equal(first(b,'intake')['Service Needed'][0].name,'Not Sure');});
test('corroborated existing Lead and its Client are reused and linked',async()=>{
 const b=new FakeBase();const client=b.seed('clients',{'Client Name':'[JEF INTAKE QA] River Events',Email:'billing@example.invalid'});
 const lead=b.seed('leads',{'Lead ID':'QA-LEAD-1',Business:'[JEF INTAKE QA] River Events',Emails:'qa.alex@example.invalid','Client Record':[{id:client}]});
 const r=await reconcile(env('client','9000000000000000001',{27:'QA-LEAD-1'}),b);assert.equal(r.status,'done');assert.equal(b.data.clients.size,1);assert.equal(first(b,'intake').Leads[0].id,lead);assert.equal(first(b,'intake')['Converted Client'][0].id,client);
});
test('unverified hidden Lead ID cannot create an account or relationship',async()=>{
 const b=new FakeBase();b.seed('leads',{'Lead ID':'QA-LEAD-1',Business:'Other Company',Emails:'someone@example.invalid'});
 const r=await reconcile(env('client','9000000000000000001',{27:'QA-LEAD-1'}),b);assert.equal(r.status,'exception');assert.equal(b.data.clients.size,0);assert.equal(first(b,'intake').Leads,undefined);
});

test('Conversational remains the exact reported English level',async()=>{const b=new FakeBase();const r=await reconcile(env('candidate','9000000000000000001',{14:'Conversational'}),b);assert.equal(r.status,'done');assert.equal(first(b,'candidates')['English Level'].name,'Conversational');});
