import assert from "node:assert/strict";
import test from "node:test";
import { AirtableOutreachGates, JEF_AIRTABLE } from "../src/airtable-gates.js";

const ids={activity:"recAAAAAAAAAAAAAA",lead:"recBBBBBBBBBBBBBB",campaign:"reclIlbWpaTcMrc18",command:"recpYdDfwJjrpUwyX"};
const payload={contractVersion:"outreach-v2",suppressionCleared:true,campaignId:"JEF-CAMPAIGN",leadId:"LEAD-1",messageVersion:"v4.1",sequenceStep:"FIRST-TOUCH",destination:"person@example.com",subject:"Subject",textBody:"Body",sequenceInstanceKey:"SEQ-1",sequenceVersionSnapshot:"SEQ-v1",templateVersionSnapshot:"v4.1",senderIdentitySnapshot:"hello@jefscouting.com",verifiedRecipient:"person@example.com",finalSubjectSnapshot:"Subject",finalBodySnapshot:"Body",priorContactSnapshot:"CLEAR",airtableActivityRecordId:ids.activity,airtableLeadRecordId:ids.lead,airtableCampaignRecordId:ids.campaign,airtableCommandRecordId:ids.command,runtimeMode:"production"};
const effectKey="OUTREACH-SEND|JEF-CAMPAIGN|LEAD-1|v4.1|FIRST-TOUCH";
const F=JEF_AIRTABLE.fields;
function records({paused=false,suppression=[]}={}) { return {
  [ids.activity]:{id:ids.activity,fields:{[F.activity.lead]:[ids.lead],[F.activity.campaign]:[ids.campaign],[F.activity.effectKey]:effectKey,[F.activity.state]:"READY",[F.activity.contractGate]:"PASS — EFFECT READY",[F.activity.payloadGate]:"PASS — CORE PAYLOAD FROZEN",[F.activity.recipient]:payload.destination,[F.activity.prior]:"CLEAR",[F.activity.suppression]:"CLEAR",[F.activity.sequenceInstance]:payload.sequenceInstanceKey,[F.activity.sequenceVersion]:payload.sequenceVersionSnapshot,[F.activity.templateVersion]:payload.templateVersionSnapshot,[F.activity.subject]:payload.subject,[F.activity.body]:payload.textBody,[F.activity.sender]:payload.senderIdentitySnapshot}},
  [ids.lead]:{id:ids.lead,fields:{[F.lead.id]:payload.leadId,[F.lead.recipient]:payload.destination,[F.lead.dnc]:false,[F.lead.suppressionRecords]:suppression,[F.lead.suppressionStatus]:"Clear",[F.lead.admission]:"READY",[F.lead.admissionGate]:"PASS — CONCATENATION CANDIDATE",[F.lead.responsePriority]:"P5 — NEW FIRST TOUCH",[F.lead.nextAction]:"FIRST_TOUCH",[F.lead.campaigns]:[ids.campaign]}},
  [ids.campaign]:{id:ids.campaign,fields:{[F.campaign.id]:payload.campaignId,[F.campaign.status]:paused?"Paused":"Running",[F.campaign.runtime]:"Running",[F.campaign.circuit]:"Healthy",[F.campaign.runtimeGate]:"READY — V2 AUTONOMOUS RUNTIME",[F.campaign.engineVersion]:"OUTREACH-v2",[F.campaign.commands]:[ids.command]}},
  [ids.command]:{id:ids.command,fields:{[F.command.id]:"CMD-1",[F.command.state]:"In Progress",[F.command.approval]:"Approved",[F.command.gate]:"Approved",[F.command.integrity]:"READY",[F.command.health]:"ACTIVE",[F.command.campaigns]:[ids.campaign]}}
}; }
function gate(dataset){return new AirtableOutreachGates({client:{async getRecord(_table,id){if(!dataset[id]) throw new Error("missing"); return structuredClone(dataset[id]);}},commandRecordId:ids.command,campaignRecordId:ids.campaign,correlationDomain:"jefscouting.com"});}

test("exact canonical IDs and all current gates authorize",async()=>{const binding=await gate(records()).readCurrent({payload,effectKey});assert.equal(binding.decision,"AUTHORIZED");assert.equal((await gate(records()).revalidate({payload,effectKey,payloadFingerprint:binding.payloadFingerprint})).suppressionCleared,true);});
test("paused Campaign fails closed",async()=>assert.equal((await gate(records({paused:true})).readCurrent({payload,effectKey})).decision,"HOLD"));
test("active linked suppression fails closed",async()=>{const suppressionId="recSSSSSSSSSSSSSS";const data=records({suppression:[suppressionId]});data[suppressionId]={id:suppressionId,fields:{[F.suppression.status]:"Active",[F.suppression.integrity]:"PASS"}};const binding=await gate(data).readCurrent({payload,effectKey});assert.equal(binding.decision,"AUTHORIZED");assert.equal((await gate(data).revalidate({payload,effectKey,payloadFingerprint:binding.payloadFingerprint})).suppressionCleared,false);});
test("pinned authority IDs cannot be redirected",async()=>{const bad={...payload,airtableCommandRecordId:"recEEEEEEEEEEEEEE"};await assert.rejects(gate(records()).readCurrent({payload:bad,effectKey}),/PINNED_AUTHORITY_RECORD_MISMATCH/);});
